# Multiple Uploads?
# Folders in the media library?
# Load captions from image metadata?
# PW protected pages
# Debug about page

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:

  - name: 'project'
    label: 'Project'
    folder: 'content/project'
    create: true
    slug: '{{year}}-{{month}}-{{slug}}'
    editor:
      preview: true
      draft: true
    fields: # optional video field
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: "Ongoing", name: "ongoing", widget: "boolean", default: false }
      - { label: 'Teaser Description', name: 'teaser_description', widget: 'string' }
      - { label: "Teaser Image", name: "teaser_image", widget: "image", required: true }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Thumbnail Images'
        name: 'thumbnail_images'
        widget: 'list'
        fields:
          - label: Images
            name: images
            widget: list
            fields: { label: Image, name: image, widget: image }

  - name: 'story'
    label: 'Story'
    folder: 'content/story'
    create: true
    slug: '{{year}}-{{month}}-{{slug}}'
    editor:
      preview: true
      draft: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' } # Remove, text field for location & year is enough
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Publication', name: 'publication', widget: 'string' }
      - { label: "Ongoing", name: "ongoing", widget: "boolean", default: false }
      - { label: 'Teaser Description', name: 'teaser_description', widget: 'string' }
      - { label: "Teaser Image", name: "teaser_image", widget: "image", required: true }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Thumbnail Images'
        name: 'thumbnail_images'
        widget: 'list'
        fields:
          - label: 'Image'
            name: 'image'
            widget: image
          - label: 'Caption'
            name: 'caption'
            widget: string

  - name: 'portrait'
    label: 'Portrait'
    folder: 'content/portrait'
    create: true
    slug: '{{year}}-{{month}}-{{slug}}'
    editor:
      preview: true
      draft: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Caption', name: 'caption', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: 'tearsheet'
    label: 'Tearsheet'
    folder: 'content/tearsheet'
    create: true
    slug: '{{year}}-{{month}}-{{slug}}'
    editor:
      preview: true
      draft: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Caption', name: 'caption', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: 'video'
    label: 'Video'
    folder: 'content/video'
    create: true
    slug: '{{year}}-{{month}}-{{slug}}'
    editor:
      preview: true
      draft: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Vimeo Video ID', name: 'vimeo_video_id', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/_index.md'
        label: 'Home Page'
        name: 'home'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Body (Optional), name: body, widget: markdown, required: false }
          - { label: Image (Optional), name: image, widget: image, required: false }
      - file: 'content/pages/projects.md'
        label: 'Projects Page'
        name: 'projects'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Body (Optional), name: body, widget: markdown, required: false }
          - { label: Image (Optional), name: image, widget: image, required: false }
      - file: 'content/pages/stories.md'
        label: 'Stories Page'
        name: 'stories'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Body (Optional), name: body, widget: markdown, required: false }
          - { label: Image (Optional), name: image, widget: image, required: false }
      - file: 'content/pages/portraits.md'
        label: 'Portraits Page'
        name: 'portraits'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Body (Optional), name: body, widget: markdown, required: false }
          - { label: Image (Optional), name: image, widget: image, required: false }
      - file: 'content/pages/videos.md'
        label: 'Videos Page'
        name: 'videos'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Body (Optional), name: body, widget: markdown, required: false }
          - { label: Image (Optional), name: image, widget: image, required: false }
      - file: 'content/pages/about.md'
        label: 'About Page'
        name: 'about'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Body (Optional), name: body, widget: markdown, required: false }
          - { label: Image (Optional), name: image, widget: image, required: false }
      - file: 'content/pages/tearsheets.md'
        label: 'Tearsheets Page'
        name: 'tearsheets'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Body (Optional), name: body, widget: markdown, required: false }
          - { label: Image (Optional), name: image, widget: image, required: false }

